# Generated by Django 5.2.8 on 2025-11-27 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barcos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contenedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_contenedor", models.CharField(max_length=50, unique=True)),
                ("tipo", models.CharField(max_length=50)),
                ("peso", models.FloatField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "barco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contenedores",
                        to="barcos.barco",
                    ),
                ),
            ],
            options={
                "db_table": "contenedores",
            },
        ),
    ]
