# Generated by Django 5.2.8 on 2025-11-27 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autorizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateField()),
                ("tipo_autorizacion", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "autorizaciones",
            },
        ),
    ]
