# Generated by Django 5.2.8 on 2025-11-27 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barcos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tripulante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=50)),
                ("nacionalidad", models.CharField(max_length=50)),
                ("identificacion", models.CharField(max_length=50)),
                (
                    "barco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tripulacion",
                        to="barcos.barco",
                    ),
                ),
            ],
            options={
                "db_table": "tripulacion",
            },
        ),
    ]
