# Generated by Django 5.2.8 on 2025-11-27 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspeccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateField()),
                ("resultado", models.CharField(max_length=50)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "contenedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspecciones",
                        to="contenedores.contenedor",
                    ),
                ),
            ],
            options={
                "db_table": "inspecciones",
            },
        ),
    ]
